/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

// source: /Users/los/dev/tubular/ccapi/binding/build/go/swig_interface.i

#ifndef SWIG_ccapi_WRAP_H_
#define SWIG_ccapi_WRAP_H_

class Swig_memory;

class SwigDirector_EventHandler : public ccapi::EventHandler
{
 public:
  SwigDirector_EventHandler(int swig_p);
  virtual ~SwigDirector_EventHandler();
  bool _swig_upcall_processEvent(ccapi::Event const &event,ccapi::Session *sessionPtr) {
    return ccapi::EventHandler::processEvent(event,sessionPtr);
  }
  virtual bool processEvent(ccapi::Event const &event,ccapi::Session *sessionPtr);
 private:
  intgo go_val;
  Swig_memory *swig_mem;
};

class SwigDirector_Logger : public ccapi::Logger
{
 public:
  SwigDirector_Logger(int swig_p);
  virtual ~SwigDirector_Logger();
  void _swig_upcall_logMessage(std::string const &severity,std::string const &threadId,std::string const &timeISO,std::string const &fileName,std::string const &lineNumber,std::string const &message) {
    ccapi::Logger::logMessage(severity,threadId,timeISO,fileName,lineNumber,message);
  }
  virtual void logMessage(std::string const &severity,std::string const &threadId,std::string const &timeISO,std::string const &fileName,std::string const &lineNumber,std::string const &message);
 private:
  intgo go_val;
  Swig_memory *swig_mem;
};

#endif
